### ISSUE TITLE
Blogger down

### ISSUE THREAD

**Issue by jcmundy** [lib-uoguelph-ca/omeka-blogger#1]
I have been using blogger on a site with multiple RSS feeds.  I have only had the page crash if a feed goes down.  Right now though I cannot get the page to load unless I remove all RSS feeds.  Is there another setting that would error and blank the page?  Thank you so much!

**Comment by jcmundy** [comment]
I found that one of the urls had a redirect, so I had to add the new url.  Thank you.

**Comment by doana** [comment]
Thanks for the update! 

In general, I would like to improve the error handling so that a bad feed URL doesn't fail quite so spectacularly. Hopefully doing so will help prevent issues like this in the future.

**Comment by barrystep** [comment]
Hi: does anyone know whether Blogger is working? I've installed the plugin, but the shortcode isn't pulling the feed into my simple page.

**Comment by doana** [comment]
@barrystep 

I just spun up a new instance of Omeka 2.7 on php 7.3.9 with the v1.1.1 of the plugin. Using a wordpress blog feed I was able to pull in the feed content without any issues. 

Some questions: 
- What shortcode are you using exactly?
- Can you check your PHP error log to see if anything unusual pops up when you try to view the page with the blog in it?

**Comment by doana** [comment]
Haven't heard back so I'm going to assume you've sorted this out. Feel free to reopen if you're still having issues!
