### ISSUE TITLE
Error: non-static method BloggerPlugin::renderBlog() cannot be called statically

### ISSUE THREAD

**Issue by adehner** [lib-uoguelph-ca/omeka-blogger#3]
I'm testing out Omeka Blogger on a fresh instance of Omeka 3.1.2 and an instance of Omeka 2.8. Edit to add that I've tested with PHP 8 and PHP 7.4 with same results.

When loading a simple page with the blog shortcode, I see no content. Both error logs show the error below. I've tried a couple of different wordpress feed urls: https://elaboratories.org/feed/ and https://janeaddams.ramapo.edu/feed/ 

I'm adding the shortcode like this: [blog url=https://elaboratories.org/feed/]

[07-Feb-2024 20:26:36 UTC] PHP Fatal error:  Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, non-static method BloggerPlugin::renderBlog() cannot be called statically in /home/annelies/public_html/englewood/application/views/helpers/Shortcodes.php:80
Stack trace:
#0 [internal function]: Omeka_View_Helper_Shortcodes->handleShortcode(Array)
#1 /home/annelies/public_html/englewood/application/views/helpers/Shortcodes.php(63): preg_replace_callback('/\\[(\\w+)\\s*([^\\...', Array, '[blog url=https...')
#2 /home/annelies/public_html/englewood/application/libraries/Zend/View/Abstract.php(350): Omeka_View_Helper_Shortcodes->shortcodes('[blog url=https...')
#3 /home/annelies/public_html/englewood/plugins/SimplePages/views/public/page/show.php(20): Zend_View_Abstract->__call('shortcodes', Array)
#4 /home/annelies/public_html/englewood/application/libraries/Omeka/View.php(114): include('/home/annelies/...')
#5 /home/annelies/public_html/englewood/application/libraries/Zend/View/Abstract.php(889): Omeka_View->_run('/home/annelies/...')
#6 /home/annelies/public_html/englewood/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render(NULL)
#7 /home/annelies/public_html/englewood/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('page/show.php', NULL)
#8 /home/annelies/public_html/englewood/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->render()
#9 /home/annelies/public_html/englewood/application/libraries/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#10 /home/annelies/public_html/englewood/application/libraries/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#11 /home/annelies/public_html/englewood/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('showAction')
#12 /home/annelies/public_html/englewood/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#13 /home/annelies/public_html/englewood/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(106): Zend_Controller_Front->dispatch()
#14 /home/annelies/public_html/englewood/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#15 /home/annelies/public_html/englewood/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#16 /home/annelies/public_html/englewood/index.php(23): Omeka_Application->run()
#17 {main}
  thrown in /home/annelies/public_html/englewood/application/views/helpers/Shortcodes.php on line 80

**Comment by Donquiweb** [comment]
Hi,
while testing this module today under PHP 8.1.4 I encountered same issue :
`[09-Feb-2024 19:01:08 UTC] PHP Fatal error:  Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, non-static method BloggerPlugin::renderBlog() cannot be called statically in ***\application\views\helpers\Shortcodes.php:80`

and fixed it by updating this line in \plugins\Blogger\BloggerPlugin.php : 
`public function renderBlog($args, $view) {`

to 
`public static function renderBlog($args, $view) {`

**Comment by adehner** [comment]
Update to say that I tested some non-wordpress feeds, and they work for Omeka v.2 and v.3. So the plugin works great! False alarm.

In case this is useful for anyone who comes across this, I used a [feed validator](https://validator.w3.org/feed/check.cgi?) to test the rss feeds that were not working. The feeds did not validate. Once the feeds were corrected, they showed up in an Omeka simple page.
